from importlib import import_module

for module_name in (
    "actions.network.network_list_adapters",
    "actions.network.network_reachability_check",
    "actions.network.network_tool_3",
    "actions.network.network_tool_4",
    "actions.network.network_tool_5",
    "actions.network.network_tool_6",
    "actions.network.network_tool_7",
    "actions.network.network_tool_8",
    "actions.network.network_tool_9",
    "actions.network.network_tool_10",
    "actions.network.network_tool_11",
    "actions.network.network_tool_12",
    "actions.network.network_tool_13",
    "actions.network.network_tool_14",
    "actions.network.network_tool_15",
    "actions.network.network_tool_16",
    "actions.network.network_tool_17",
    "actions.network.network_tool_18",
    "actions.network.network_tool_19",
    "actions.network.network_tool_20",
    "actions.network.network_tool_21",
    "actions.network.network_tool_22",
    "actions.network.network_tool_23",
    "actions.network.network_tool_24",
    "actions.network.network_tool_25",
    "actions.network.network_tool_26",
    "actions.network.network_tool_27",
    "actions.network.network_tool_28",
    "actions.network.network_tool_29",
    "actions.network.network_tool_30",
):
    import_module(module_name)
