from importlib import import_module

for module_name in (
    "actions.browser_dom.tool_1",
    "actions.browser_dom.tool_2",
    "actions.browser_dom.tool_3",
    "actions.browser_dom.tool_4",
    "actions.browser_dom.tool_5",
    "actions.browser_dom.tool_6",
    "actions.browser_dom.tool_7",
    "actions.browser_dom.tool_8",
    "actions.browser_dom.tool_9",
    "actions.browser_dom.tool_10",
    "actions.browser_dom.tool_11",
    "actions.browser_dom.tool_12",
    "actions.browser_dom.tool_13",
    "actions.browser_dom.tool_14",
    "actions.browser_dom.tool_15",
    "actions.browser_dom.tool_16",
    "actions.browser_dom.tool_17",
    "actions.browser_dom.tool_18",
    "actions.browser_dom.tool_19",
    "actions.browser_dom.tool_20",
    "actions.browser_dom.tool_21",
    "actions.browser_dom.tool_22",
    "actions.browser_dom.tool_23",
    "actions.browser_dom.tool_24",
    "actions.browser_dom.tool_25",
    "actions.browser_dom.tool_26",
    "actions.browser_dom.tool_27",
    "actions.browser_dom.tool_28",
    "actions.browser_dom.tool_29",
    "actions.browser_dom.tool_30",
    "actions.browser_dom.tool_31",
    "actions.browser_dom.tool_32",
    "actions.browser_dom.tool_33",
    "actions.browser_dom.tool_34",
    "actions.browser_dom.tool_35",
    "actions.browser_dom.tool_36",
    "actions.browser_dom.tool_37",
    "actions.browser_dom.tool_38",
    "actions.browser_dom.tool_39",
    "actions.browser_dom.tool_40",
):
    import_module(module_name)
from actions.browser_dom.dom_gen import *  # noqa: F401,F403
